!------------------------------------------------------------------------------------------
!
! hammoz_aerocomctl.inc
!
!------------------------------------------------------------------------------------------
!
! variable name   & description & default \\
!
!------------------------------------------------------------------------------------------
NAMELIST /hammoz_aerocomctl/ &
    lTraj           , & ! switch for 'Traj' diags
    lHEmon          , & ! switch for 'HEmon' diags
    lHEaci          , & ! switch for 'HEaci' diags
    lHEpro          , & ! switch for 'HEpro' diags
    lMMPPE          , & ! switch for 'MMPPE' diags
    lAP3M           , & ! switch for 'AP3M' diags
    lAP3D               ! switch for 'AP3D' diags
