#!/bin/bash
# 
# Jobscript toolkit version 1.2 (March  2016, svn revision r3070). 
#


#-------------------------------------------------------------------------------------------------------
#
# Sylvaine Ferrachat / Grazia Frontoso 2012
#
#
# Set the variables for running echam 
# This file is sourced in jobsubm_echam.sh
#
# The task of creating the symlinks to input files is done elsewhere (see jobsubm_echam.sh),
# to avoid cluttering this settings file
#
# This file comprises 4 main chapters, where you should adjust your settings:
#   - General settings
#   - Compute settings
#   - ECHAM(-HAMMOZ) settings
#   - Settings for launching a slave p-proc job at the end of each echam integration
#
#-------------------------------------------------------------------------------------------------------

set -e

#------------------------------------------------------------------------------------------------------
#-- General settings:

model_dir="/home/ybhatti/yusufb/Branches/PPE_Aerosol/"
exp="PPE_Default"
script_dir="/home/ybhatti/yusufb/Branches/PPE_Aerosol/my_experiments/snellius/PPE_Default/"
echam_jobscript=${script_dir}/echam_jobscript_${exp}.sh # echam batch job script name

make_source_backup=false   # set to true if you want to keep records of the current state of your code
                          # it will create a text file named "source_info_[exp]_YYYY-MM-DD_HH.mm.txt"
                          # where you'll find all details (base version number, differences to base version
                          # and how to restore your code in future)
                          # !!WARNING!! it only works if your code is a working copy from an svn repository
                          #             In the opposite case, make_source_backup will be automatically reset
                          #             to false.

#------------------------------------------------------------------------------------------------------
#-- Compute settings for machine: snellius (linux_debain)

queue_name="genoa"                         # queue name to use on current batch system
jobname="$exp"                          # batch job name
ncpus=192                                # total number of cpus
walltime="10:00:00"                     # job estimated runtime
nproma=40                               # vector length (don't modify if you don't know about it)
account="srsei9480"
email="y.bhatti@sron.nl"
exp_dir="/home/ybhatti/prjs1076/PPE_Output/PPE_Experiments/${exp}/"

#-Body-begin. Do not delete this line!
#------------------------------------------------------------------------------------------------------
#-- ECHAM6-HAMMOZ settings:

   #-- General:

model_type="echam6-ham"                           # model type (echam5.5-ham, echam6, echam6-ham, etc...)
model_bin=${model_dir}/bin/echam6                 # model bin name
emissions_spec=${script_dir}/emi_spec_${exp}.txt  # name of your exp emi_spec file to copy to $exp_dir

hres="T63"                    # horizontal spectral truncation
vres="L47"                    # vertical resolution
oceres="GR15"                 # resolution of the ocean model used to produce the land-sea mask
ntiles=11                     # number of tiles in the vegetation model

no_cycles=15                  # number of cycles in one integration (1 cycle = timespan between 2 'putrerun' events)

faked_restart=true
parent_restart_dir="/home/ybhatti/prjs1076/Restart_Files/PPE_20090901_Restart_Control"
parent_current_date="20090829234500"
init_restart_flag=.false.     # echam restart flag at launch of this job 
                              # (in case of job chaining, the proper rerun flag will be automatically 
                              #  set when further jobs will be started)

date_start="2009,09,01,0,0,0"  # 20090829234500
date_stop="2011,01,01,1,0,0"

input_files_version="v0002_input"
scenario="RCP45"              # in case it is relevant for the given setup (using either variable GHG's
                              # ozone or climatologic aerosols, AND the experiment's time range 
                              # overlaps with [2009,2100]), choose here the scenario you'd like
                              # (RCP45, XXX, all case insensitive)

   #-- ECHAM6-HAMMOZ namelists:

       #-- ECHAM:

cat > ${script_dir}/namelist_${exp}.echam << EOF
&PARCTL
 nproca = WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID VALUE HERE
 nprocb = WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID VALUE HERE
/
&RUNCTL 
 nproma         = ${nproma}
 lresume        = $init_restart_flag,
 dt_resume      = 2009,08,29,23,45,0
 lmidatm        = .true.
 out_datapath   = "$exp_dir"
 out_expname    = "$exp"
 out_filetype   = 6     ! 1--> grib; 2--> NetCDF; 6--> NetCDF4;
 trac_filetype  = 2     ! 1--> grib; 2--> NetCDF;
 rerun_filetype = 4     ! 2--> NetCDF; 4--> NetCDF2
 dt_start       = $date_start
 dt_stop        = $date_stop
 putdata        = 1,'days','last',0
 trigfiles      = 2,'months','first',0
 putrerun       = 2,'months','last',0
 no_cycles      = ${no_cycles}, 
 lamip          = .false.
 lnudge         = .true.
 ldebugs        = .false.
 ltimer         = .false.
/
&SUBMODELCTL
 lmethox          = .true.
 lham             = .true.
 lbioemi_stdalone = .false.
 lmoz             = .false.
 lhammoz          = .false.
 lburden          = .true.
 emi_basepath     = "[WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID PATH HERE]"
 emi_scenario     = "${scenario}"
/
&SUBMDIAGCTL
 vphysc_lpost     = .true.
 vphyscnam        = 'all'
 wetdep_lpost     = .true. 
 wetdepnam        = 'default' 
 wetdep_gastrac   = 'SO2', 'H2SO4'
 wetdep_keytype   = 3          ! BYTRACER=1; BYSPECIES=2; BYMODE=3
 drydep_lpost     = .true. 
 drydepnam        = 'all' 
 drydep_gastrac   = 'SO2', 'H2SO4'
 drydep_keytype   = 2          ! BYTRACER=1; BYSPECIES=2; BYMODE=3
 sedi_lpost       = .true. 
 sedinam          = 'all'
 sedi_keytype     = 2          ! BYTRACER=1; BYSPECIES=2; BYMODE=3 
 emi_lpost        = .true.
 emi_lpost_sector = .true.
 eminam           = 'all'
 emi_gastrac      = 'all'
/
&DEBUGSCTL
 putdebug_stream = 1, 'days', 'last', 0
/
&RADCTL
 iaero   = 1     ! 1 for interactive (lham=true), 2 for Tanre 3 for Kinne  
 isolrad = 3      
 io3     = 4     ! 3 --> obsolete! climatology from IPCC-NetCDF file, 4--> CMIP5 new data
/
&PHYSCTL
 lcdnc_progn    = .true.
 nauto          = 2
 cdnc_min_fixed = V_SCALE_CDNC_MIN    ! V_SCALE_CDNC_MIN
/
&HAMCTL
 nseasalt       = 7
 nwetdep        = 3
 naerorad       = 1
 nraddiag       = 1
 burden_keytype = 2          ! BYTRACER=1; BYSPECIES=2;
/
&NDGCTL
 inudgformat     = 2
 dt_nudg_start   = $date_start
 dt_nudg_stop    = $date_stop
 lnudgdbx        = .false.
 lnudgini        = .false.
 nudglmin        = 1
 nudglmax        = ${vres#L}
 nudgsmin        = 0
 nudgsmax        = ${hres#T}
 lnudgimp        = .true.
 nudgt           = ${vres#L}*0.0 !SF switch off temperature nudging (recommended, see Zhang et al, ACP 2014) 
 ltintlin        = .false.
 ldamplin        = .true.
 nudgdamp        = 1.
 nudgdsize       = 0.5
 ndg_file_nc    = "ndg%y4%m2.nc"
/
&set_stream
  stream='accw'
  lpost=0 
/
&set_stream
  stream='co2'
  lpost=0
/
&set_stream
  stream='conv'
  lpost=0
/
&set_stream
  stream='drydep'
  lpost=0
/
&set_stream
  stream='wetdep'
  lpost=0
/
&set_stream
  stream='land'
  lpost=0
/
&set_stream
  stream='nudg'
  lpost=0
/
&set_stream
  stream='sedi'
  lpost=0
/
&set_stream
  stream='echamm'
  lpost=0 
/
&set_stream
  stream='jsbash'
  lpost=0
/
&set_stream
  stream='veg'
  lpost=0
/
&set_stream
  stream='activ'
  lpost=1
  interval = 1,'months','last',0
/
&set_stream
  stream='ham'
  lpost=1
  interval = 1,'months','last',0
/
&set_stream
  stream='tracer'
  lpost=1
  interval = 1,'months','last',0
/
&HAMMOZ_PERTURBATIONS
  scale_nuc_ft     = V_SCALE_NUC_FT   ! V_SCALE_NUC_FT
  scale_emi_cmr_ff = V_SCALE_EMI_CMR_FF   ! V_SCALE_EMI_CMR_FF
  scale_emi_cmr_bb = V_SCALE_EMI_CMR_BB   ! V_SCALE_EMI_CMR_BB
  scale_emi_cmr_bf = V_SCALE_EMI_CMR_BF   ! V_SCALE_EMI_CMR_BF
  scale_emi_ff     = V_SCALE_EMI_FF  ! V_SCALE_EMI_FF
  scale_emi_bb     = V_SCALE_EMI_BB  ! V_SCALE_EMI_BB
  scale_emi_bf     = V_SCALE_EMI_BF  ! V_SCALE_EMI_BF
  scale_emi_dms    = V_SCALE_EMI_DMS  ! V_SCALE_EMI_DMS
  scale_emi_ssa    = V_SCALE_EMI_SSA  ! V_SCALE_EMI_SSA
  scale_emi_so2    = V_SCALE_EMI_ANTH_SO2 ! V_SCALE_EMI_ANTH_SO2
  scale_emi_du     = V_SCALE_EMI_DUST ! V_SCALE_EMI_DUST
  scale_drydep_ait = V_SCALE_DRYDEP_AIT   ! V_SCALE_DRYDEP_AIT
  scale_drydep_acc = V_SCALE_DRYDEP_ACC   ! V_SCALE_DRYDEP_ACC
  scale_drydep_coa = V_SCALE_DRYDEP_COA   ! V_SCALE_DRYDEP_COA
  scale_wetdep_ic = V_SCALE_WETDEP_IC     ! V_SCALE_WETDEP_IC
  scale_wetdep_bc = V_SCALE_WETDEP_BC     ! V_SCALE_WETDEP_BC
  bc_rad_ni 	  = V_SCALE_BC_RAD_NI  ! V_SCALE_BC_RAD_NI
  du_rad_ni  	  = V_SCALE_DU_RAD_NI  ! V_SCALE_DU_RAD_NI
  scale_so4_coating = V_SCALE_SO4_COATING  ! V_SCALE_SO4_COATING
  scale_kappa_ss   = V_SCALE_KAPPA_SS ! V_SCALE_KAPPA_SS
  scale_kappa_so4  = V_SCALE_KAPPA_SO4 ! V_SCALE_KAPPA_SO4
  pH_pert          = V_SCALE_PH_PERT ! V_SCALE_PH_PERT
  scale_so2_reactions = V_SCALE_SO2_REACTIONS ! V_SCALE_SO2_REACTIONS
  scale_vertical_velocity = V_SCALE_VERTICAL_VELOCITY ! V_SCALE_VERTICAL_VELOCITY


/
EOF

       #-- JS-BACH:

cat > ${script_dir}/namelist_${exp}.jsbach <<EOF
&JSBACH_CTL
  standalone = .false.
  ntiles = ${ntiles}

  ! --- options to activate the different jsbach modules ---
  use_bethy = .true.
  use_phenology = .true.
  use_albedo = .true.
  use_roughness_lai = .true.
  use_roughness_oro = .false.
  test_cconservation = .true.

  ! --- output options ---
  file_type = 2
  veg_at_1200 = .false.
/
&SOIL_CTL
  nsoil =5
/
EOF

       #-- Mean-values streams:

cat >> ${script_dir}/namelist_${exp}.echam << EOF
&MVSTREAMCTL
 interval = 1,'months','last',0
 filetag = 'echamm'
 source  = 'sp', 'gl', 'g3b'
/
!SF Further example of online mean setup (simpler than for the echam stream)
!   Uncomment / amend if needed
!&MVSTREAMCTL
! interval = 1,'months','last',0
! source  = 'activ'
! meannam = ''
/
EOF

#-Body-end. Do not delete this line!

#------------------------------------------------------------------------------------------------------
#-- Settings for launching a slave p-proc job at the end of each echam integration
#   This may be specific for machine: snellius (linux_debain)

flag_p_proc=false                                         # flag to launch the p-proc
p_proc_script="/path/to/some/post-processing script"      # p-proc script (no batch directives in there)
p_proc_dir="/path/to/post_proc_disk/${USER}/${exp}"       # remote directory where p_proc is done
p_proc_jobname="p-proc"                                   # batch jobname for executing the p_proc_script
p_proc_walltime="24:00:00"
