#!/bin/bash

#-------------------------------------------------------------------------------------------------------
# Sylvaine Ferrachat 2012
# 
# The following is the body part of a settings file that will be sourced 
# by jobsubm_echam.sh to setup and launch an echam job.
#
# The task of assembling together all the pieces of the settings file is done by prepare_run.sh.
#
# These pieces are:
#
#     - Header: general settings and compute settings:
#               - there are mostly machine-dependent, and not echam version-dependent
#               --> to be found in each machine_config/machine_name/
#
#     - Body: echam(-hammoz) settings: 
#               - these are machine-independent, and echam version-dependent
#               --> to be found in the model distribution (distribution default templates), in
#                   any user's already existing settings, or in run_configs/ as a rescue for model versions
#                   older than the first inclusion of this into echam distributions
#
#     - Tail: settings for launching any arbitrary slave p-proc job at the end of each echam integration:
#               - these are machine-dependent, and echam version-independent
#               --> to be found in each machine_config/machine_name/
#
#-------------------------------------------------------------------------------------------------------

#-Body-begin. Do not delete this line!
#------------------------------------------------------------------------------------------------------
#-- ECHAM6-HAMMOZ settings:

   #-- General:

model_type="echam6-ham"                           # model type (echam5.5-ham, echam6, echam6-ham, etc...)
model_bin=${model_dir}/bin/echam6                 # model bin name
emissions_spec=${script_dir}/emi_spec_${exp}.txt  # name of your exp emi_spec file to copy to $exp_dir

hres="T63"                    # horizontal spectral truncation
vres="L47"                    # vertical resolution
oceres="GR15"                 # resolution of the ocean model used to produce the land-sea mask
ntiles=11                     # number of tiles in the vegetation model

no_cycles=42                  # number of cycles in one integration (1 cycle = timespan between 2 'putrerun' events)
init_restart_flag=.false.     # echam restart flag at launch of this job 
                              # (in case of job chaining, the proper rerun flag will be automatically 
                              #  set when further jobs will be started)

date_start="2002,10,01,0,0,0" # start of the experiment - Should never be modified when making a rerun
date_stop="2013,01,01,0,0,0"  # end of the experiment - Can be freely adjusted during the whole experiment

input_files_version="v0002"   # version label for input files !!do not change if you don't know about it!!
scenario="RCP45"              # in case it is relevant for the given setup (using either variable GHG's
                              # ozone or climatologic aerosols, AND the experiment's time range 
                              # overlaps with [2009,2100]), choose here the scenario you'd like
                              # (RCP45, XXX, all case insensitive)

   #-- ECHAM6-HAMMOZ namelists:

       #-- ECHAM:

cat > ${script_dir}/namelist_${exp}.echam << EOF
&PARCTL
 nproca = WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID VALUE HERE
 nprocb = WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID VALUE HERE
/
&RUNCTL 
 nproma         = ${nproma}
 lresume        = $init_restart_flag,
 lmidatm        = .true.
 out_datapath   = "$exp_dir"
 out_expname    = "$exp"
 out_filetype   = 2     ! 1--> grib; 2--> NetCDF; 6--> NetCDF4;
 trac_filetype  = 2     ! 1--> grib; 2--> NetCDF;
 rerun_filetype = 4     ! 2--> NetCDF; 4--> NetCDF2
 dt_start       = $date_start
 dt_stop        = $date_stop
 putdata        = 1,'months','last',0
 trigfiles      = 1, 'months', 'first', 0
 putrerun       = 3,'months','last',0
 no_cycles      = ${no_cycles}, 
 lamip          = .false.
 lnudge         = .false.
 ldebugs        = .false.
 ltimer         = .false.
/
&SUBMODELCTL
 lmethox          = .true.
 lham             = .false.
 lbioemi_stdalone = .false.
 lmoz             = .false.
 lhammoz          = .false.
 lburden          = .true.
 emi_basepath     = "[WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID PATH HERE]"
 emi_scenario     = "${scenario}"
 lccnclim         = .true.
/
&SUBMDIAGCTL
 vphysc_lpost     = .true.
 vphyscnam        = 'all'
 wetdep_lpost     = .false. 
 wetdepnam        = 'default' 
 wetdep_gastrac   = 'SO2', 'H2SO4'
 wetdep_keytype   = 3          ! BYTRACER=1; BYSPECIES=2; BYMODE=3
 drydep_lpost     = .false. 
 drydepnam        = 'all' 
 drydep_gastrac   = 'SO2', 'H2SO4'
 drydep_keytype   = 2          ! BYTRACER=1; BYSPECIES=2; BYMODE=3
 sedi_lpost       = .false. 
 sedinam          = 'all'
 sedi_keytype     = 2          ! BYTRACER=1; BYSPECIES=2; BYMODE=3 
 emi_lpost        = .false.
 emi_lpost_sector = .true.
 eminam           = 'all'
 emi_gastrac      = 'all'
/
&DEBUGSCTL
 putdebug_stream = 1, 'days', 'last', 0
/
&RADCTL
 iaero   = 3     ! 1 for interactive (lham=true), 2 for Tanre 3 for Kinne  
 isolrad = 3      
 io3     = 4     ! 3 --> obsolete! climatology from IPCC-NetCDF file, 4--> CMIP5 new data
/
&PHYSCTL
 lclmi_progn    = .true.
 nauto          = 2
 nclmi_progn    = 3
 ncd_activ      = 1
 ldetr_liquid         = .true.
 lsedfix              = .true.
 ldetr_convicfactor   = .true.
 convicfactor         = 5.0
 lnewdiags            = .true.
 lpr_corr             = .true.
 lepsfix      = .true.
 ldyn_cdnc_min = .true.
 rcd_vol_max  = 15.0E-6
 tun47ccraut  = 3.25
 tun47cdncmin = 40.0
 tun47zinhomi = 0.7
 tun47zinhoml1= 0.8
 tun47zinhoml2= 0.4
 tun47zinhoml3= 0.8
 tun47zinpar  = 0.1
 tun47ccsaut  = 900.0
 tun47entrpen = 2.0E-4
 tun47cprcon  = 9.0E-4
 tun47entrscv = 3.0E-3
 tun47cmfctop = 0.2
 lslf         = .true.
 lccnclimdiags = .true.
/
&HAMCTL
 nseasalt       = 7
 nwetdep        = 3
 naerorad       = 1
 nraddiag       = 1
 burden_keytype = 2          ! BYTRACER=1; BYSPECIES=2;
 nccndiag       = 6
/
&CCNCLIMCTL
 ninput_type_CCN = 3
 ninput_type_IN  = 3
 l_variable_ss   = .false.
/
&NDGCTL
 inudgformat     = 2
 dt_nudg_start   = $date_start
 dt_nudg_stop    = $date_stop
 lnudgdbx        = .false.
 lnudgini        = .false.
 nudglmin        = 1
 nudglmax        = ${vres#L}
 nudgsmin        = 0
 nudgsmax        = ${hres#T}
 lnudgimp        = .true.
 nudgt           = ${vres#L}*0.0 !SF switch off temperature nudging (recommended, see Zhang et al, ACP 2014) 
 ltintlin        = .false.
 ldamplin        = .true.
 nudgdamp        = 1.
 nudgdsize       = 0.5
 ndg_file_nc    = "ndg%y4%m2.nc"
/
&SET_STREAM
 stream = 'accw'
 lpost = 0
/
&SET_STREAM
 stream = 'co2'
 lpost = 0
/
&SET_STREAM
 stream = 'conv'
 lpost = 0
/
&SET_STREAM
 stream = 'jsbach'
 lpost = 0
/
&SET_STREAM
 stream = 'land'
 lpost = 0
/
&SET_STREAM
 stream = 'surf'
 lpost = 0
/
&SET_STREAM
 stream = 'veg'
 lpost = 0
/
&SET_STREAM
 stream = 'rad'
 lpost = 0
/
&SET_STREAM
 stream = 'vphysc'
 lpost = 0
/
&SET_STREAM
 stream = 'cmpdiag'
 lpost = 0
/
&SET_STREAM_ELEMENT
 stream = 'g3b'
 name = 'tkem1'
 lpost = 1
/
&SET_STREAM_ELEMENT
 stream = 'g3b'
 name = 'tkem'
 lpost = 1
/
EOF

       #-- JS-BACH:

cat > ${script_dir}/namelist_${exp}.jsbach <<EOF
&JSBACH_CTL
  standalone = .false.
  ntiles = ${ntiles}

  ! --- options to activate the different jsbach modules ---
  use_bethy = .true.
  use_phenology = .true.
  use_albedo = .true.
  use_roughness_lai = .true.
  use_roughness_oro = .false.
  test_cconservation = .true.

  ! --- output options ---
  file_type = 2
  veg_at_1200 = .false.
/
&SOIL_CTL
  nsoil =5
/
EOF

       #-- Mean-values streams:

cat >> ${script_dir}/namelist_${exp}.echam << EOF
&MVSTREAMCTL
 interval = 1,'months','last',0
 filetag = 'echamm'
 source  = 'sp', 'gl', 'g3b'
/
&MVSTREAMCTL
 interval = 1,'months','last',0
 filetag = 'tracerm'
 source  = 'tracer'
/
!SF Further example of online mean setup (simpler than for the echam stream)
!   Uncomment / amend if needed
&MVSTREAMCTL
 interval = 1,'months','last',0
 source  = 'activ'
 meannam = 'ICC_MOD', 'MCC_MOD', 'LCC_MOD', 'NACT_STRAT_TMP', 'NACT_CONV_TMP', 'CCN_STRAT_TMP', 'CCN_CONV_TMP'
/
EOF

#-Body-end. Do not delete this line!
